"""Service-layer package for Foundation CLI."""

from foundation.services.approval import ApprovalPrompt, ApprovalService
from foundation.services.guardrails import GuardrailPolicyEngine, SimplePolicyEngine
from foundation.services.history import HistoryStore
from foundation.services.orchestrator import (
    OrchestrationError,
    OrchestrationPlanError,
    RequestOrchestrator,
)
from foundation.services.provider import (
    OllamaChatAdapter,
    OpenAIResponsesAdapter,
    ProviderAdapter,
    ProviderError,
    ProviderErrorCode,
    build_provider_adapter,
)
from foundation.services.shell import (
    ExecutionMode,
    OutputStream,
    ShellCommandRequest,
    ShellCommandResult,
    ShellExecutionCancelled,
    ShellExecutionError,
    ShellExecutionSpawnError,
    ShellExecutionTimeout,
    ShellOutputEvent,
    ShellRuntime,
)
from foundation.services.staging import WorkspaceRewriteStager
from foundation.services.tools import (
    FileDiscoveryRequest,
    FileDiscoveryResult,
    FileDiscoveryType,
    GitCommitSummary,
    GitContextRequest,
    GitContextResult,
    GitDiffStat,
    GitStatusEntry,
    HelpLookupRequest,
    HelpLookupResult,
    HelpLookupSource,
    LocalToolService,
    SearchMatch,
    SearchRequest,
    SearchResult,
    ToolAvailabilityStatus,
    ToolBinaryStatus,
    ToolError,
    ToolErrorCode,
    ToolExecutionError,
    WorkspacePathFilter,
)

__all__ = [
    "ApprovalPrompt",
    "ApprovalService",
    "ExecutionMode",
    "FileDiscoveryRequest",
    "FileDiscoveryResult",
    "FileDiscoveryType",
    "GitCommitSummary",
    "GuardrailPolicyEngine",
    "GitContextRequest",
    "GitContextResult",
    "GitDiffStat",
    "GitStatusEntry",
    "HelpLookupRequest",
    "HelpLookupResult",
    "HelpLookupSource",
    "HistoryStore",
    "LocalToolService",
    "OpenAIResponsesAdapter",
    "OllamaChatAdapter",
    "OrchestrationError",
    "OrchestrationPlanError",
    "OutputStream",
    "ProviderAdapter",
    "ProviderError",
    "ProviderErrorCode",
    "RequestOrchestrator",
    "SearchMatch",
    "SearchRequest",
    "SearchResult",
    "ShellCommandRequest",
    "ShellCommandResult",
    "ShellExecutionCancelled",
    "ShellExecutionError",
    "ShellExecutionSpawnError",
    "ShellExecutionTimeout",
    "ShellOutputEvent",
    "ShellRuntime",
    "SimplePolicyEngine",
    "ToolAvailabilityStatus",
    "ToolBinaryStatus",
    "ToolError",
    "ToolErrorCode",
    "ToolExecutionError",
    "WorkspaceRewriteStager",
    "WorkspacePathFilter",
    "build_provider_adapter",
]
